// A realistic, approximate topic-wise weightage for SSC CGL mock tests based on user input.
// This helps in generating more balanced and exam-like question papers with randomized question counts.

export const SSC_CGL_TIER1_TOPIC_DISTRIBUTION = {
    'General Intelligence & Reasoning': [
        { topicKeywords: ['blood relation'], min: 1, max: 2 },
        { topicKeywords: ['seating arrangement'], min: 0, max: 1 },
        { topicKeywords: ['paper cutting', 'paper folding'], min: 0, max: 1 },
        { topicKeywords: ['logical venn diagram'], min: 0, max: 1 },
        { topicKeywords: ['missing number series', 'number series'], min: 1, max: 3 },
        { topicKeywords: ['classification', 'odd one out'], min: 1, max: 2 },
        { topicKeywords: ['coding-decoding'], min: 2, max: 4 },
        { topicKeywords: ['dice'], min: 0, max: 2 },
        { topicKeywords: ['order and ranking'], min: 0, max: 1 },
        { topicKeywords: ['syllogism'], min: 0, max: 3 },
        { topicKeywords: ['mirror image', 'water image'], min: 0, max: 1 },
        { topicKeywords: ['symbols and notations', 'mathematical operator', 'arithmetical reasoning'], min: 0, max: 2 },
        { topicKeywords: ['analogy'], min: 0, max: 4 },
        { topicKeywords: ['alphabetical series'], min: 1, max: 3 },
    ],
    'Quantitative Aptitude': [
        { topicKeywords: ['average'], min: 0, max: 2 },
        { topicKeywords: ['algebra'], min: 1, max: 2 },
        { topicKeywords: ['boat & stream', 'boat'], min: 0, max: 1 },
        { topicKeywords: ['distance, time, and speed', 'problems based on train'], min: 0, max: 2 },
        { topicKeywords: ['geometry', 'co-ordinate geometry', 'circle', 'chords', 'tangents', 'triangle', 'quadrilaterals', 'polygons'], min: 2, max: 4 },
        { topicKeywords: ['time and work'], min: 1, max: 2 },
        { topicKeywords: ['prism', 'cone', 'cylinder', 'sphere', 'hemispheres', 'parallelepiped', 'pyramid'], min: 2, max: 4 },
        { topicKeywords: ['trigonometry'], min: 1, max: 4 },
        { topicKeywords: ['data interpretation'], min: 3, max: 6 },
        { topicKeywords: ['ratio & proportion', 'ratio'], min: 0, max: 2 },
        { topicKeywords: ['number system'], min: 1, max: 2 },
        { topicKeywords: ['ci & si', 'simple and compound interest', 'interest'], min: 0, max: 2 },
        { topicKeywords: ['profit loss & discount', 'profit and loss'], min: 1, max: 3 },
        { topicKeywords: ['mixture & alligation', 'mixture'], min: 0, max: 3 },
        { topicKeywords: ['percentages', 'percentage'], min: 0, max: 1 },
        { topicKeywords: ['partnership'], min: 0, max: 1 },
    ],
    'English Comprehension': [
        { topicKeywords: ['direct and indirect speech', 'active / passive voice'], min: 2, max: 4 },
        { topicKeywords: ['cloze passage'], min: 3, max: 5 },
        { topicKeywords: ['idioms'], min: 1, max: 2 },
        { topicKeywords: ['fill in the blanks'], min: 1, max: 4 },
        { topicKeywords: ['synonyms', 'antonyms'], min: 2, max: 4 },
        { topicKeywords: ['sentence completion'], min: 0, max: 1 },
        { topicKeywords: ['para jumbles', 'rearrangement of sentences'], min: 0, max: 3 },
        { topicKeywords: ['spelling', 'misspelt'], min: 1, max: 4 },
        { topicKeywords: ['one word substitution'], min: 0, max: 2 },
    ],
    'General Awareness': [
        { topicKeywords: ['biology'], min: 0, max: 2 },
        { topicKeywords: ['chemistry'], min: 1, max: 2 },
        { topicKeywords: ['physics'], min: 0, max: 2 },
        { topicKeywords: ['geography'], min: 1, max: 2 },
        { topicKeywords: ['economy', 'economics'], min: 1, max: 5 },
        { topicKeywords: ['history'], min: 1, max: 5 },
        { topicKeywords: ['indian polity', 'polity'], min: 1, max: 3 },
        { topicKeywords: ['current affairs', 'current events'], min: 2, max: 5 },
        { topicKeywords: ['static gk', 'culture', 'sports', 'books', 'awards'], min: 2, max: 3 },
    ],
};

export const SSC_CGL_TIER2_TOPIC_DISTRIBUTION = {
    'Mathematical Abilities': [
        { topicKeywords: ['geometry'], min: 9, max: 15 },
        { topicKeywords: ['data interpretation'], min: 5, max: 10 },
        { topicKeywords: ['average'], min: 2, max: 2 },
        { topicKeywords: ['mixture & alligation', 'mixture'], min: 2, max: 6 },
        { topicKeywords: ['time and distance'], min: 4, max: 8 },
        { topicKeywords: ['percentage'], min: 4, max: 10 },
        { topicKeywords: ['height & distance'], min: 1, max: 1 },
        { topicKeywords: ['profit, loss & discount'], min: 3, max: 7 },
        { topicKeywords: ['triangle', 'quadrilateral', 'regular polygons', 'circle', 'right prism', 'right circular cone', 'right circular cylinder', 'sphere', 'hemispheres', 'rectangular parallelepiped', 'regular right pyramid'], min: 5, max: 6 },
        { topicKeywords: ['simplification'], min: 4, max: 6 },
        { topicKeywords: ['trigonometry'], min: 5, max: 9 },
        { topicKeywords: ['algebra'], min: 3, max: 6 },
        { topicKeywords: ['number system'], min: 5, max: 6 },
        { topicKeywords: ['ratio & proportion'], min: 1, max: 3 },
        { topicKeywords: ['time and work'], min: 3, max: 4 },
        { topicKeywords: ['partnership'], min: 2, max: 3 },
        { topicKeywords: ['coordinate geometry'], min: 1, max: 1 },
        { topicKeywords: ['simple interest & compound interest'], min: 2, max: 3 },
    ],
    'English Language and Comprehension': [
        { topicKeywords: ['reading comprehension'], min: 15, max: 30 },
        { topicKeywords: ['synonyms', 'antonyms'], min: 2, max: 10 },
        { topicKeywords: ['idiom & phrases'], min: 2, max: 10 },
        { topicKeywords: ['para jumbles', 'shuffling of sentences'], min: 20, max: 25 },
        { topicKeywords: ['error spotting', 'spot the error'], min: 12, max: 15 },
        { topicKeywords: ['sentence improvement'], min: 8, max: 15 },
        { topicKeywords: ['active passive voice'], min: 10, max: 25 },
        { topicKeywords: ['direct/ indirect speech'], min: 10, max: 25 },
        { topicKeywords: ['fill in the blanks'], min: 2, max: 10 },
        { topicKeywords: ['word substitution'], min: 2, max: 10 },
        { topicKeywords: ['correct spelling', 'misspelt'], min: 1, max: 3 },
        { topicKeywords: ['cloze test'], min: 0, max: 30 },
    ],
    // Other sections for Tier 2 can be added here following the same structure.
    'Reasoning and General Intelligence': SSC_CGL_TIER1_TOPIC_DISTRIBUTION['General Intelligence & Reasoning'], // Reuse for simplicity until specific Tier 2 data is needed
    'General Awareness': SSC_CGL_TIER1_TOPIC_DISTRIBUTION['General Awareness'],
    'Computer Knowledge Test': [
        { topicKeywords: ['ms office', 'ms word', 'ms excel', 'powerpoint'], min: 4, max: 8 },
        { topicKeywords: ['cpu', 'memory', 'input/output', 'organization'], min: 2, max: 5 },
        { topicKeywords: ['operating system', 'windows', 'keyboard shortcuts'], min: 2, max: 5 },
        { topicKeywords: ['networking', 'internet', 'e-mail', 'web browsing', 'e-banking'], min: 2, max: 5 },
        { topicKeywords: ['security', 'virus', 'hacking'], min: 1, max: 3 },
    ],
};