

import React, { useState } from 'react';
import { Difficulty, TNPSCGroupFilterType } from '../types';

interface MockTestViewProps {
    onStartTest: (difficulty: Difficulty) => void;
    activeTNPSCGroupFilter: TNPSCGroupFilterType;
}

const group1Sections = [
    { name: 'General Studies', questions: 175, color: 'bg-amber-500/10', textColor: 'text-amber-300', border: 'border-l-4 border-amber-400' },
    { name: 'Maths (Aptitude & Reasoning)', questions: 25, color: 'bg-rose-500/10', textColor: 'text-rose-300', border: 'border-l-4 border-rose-400' },
];

const otherGroupsSections = [
    { name: 'General English', questions: 100, color: 'bg-sky-500/10', textColor: 'text-sky-300', border: 'border-l-4 border-sky-400' },
    { name: 'General Studies', questions: 75, color: 'bg-amber-500/10', textColor: 'text-amber-300', border: 'border-l-4 border-amber-400' },
    { name: 'Maths (Aptitude & Reasoning)', questions: 25, color: 'bg-rose-500/10', textColor: 'text-rose-300', border: 'border-l-4 border-rose-400' },
];

const difficulties: Difficulty[] = ['Easy', 'Medium', 'Hard', 'Mixed'];

const MockTestView: React.FC<MockTestViewProps> = ({ onStartTest, activeTNPSCGroupFilter }) => {
    const [selectedDifficulty, setSelectedDifficulty] = useState<Difficulty>('Mixed');
    
    const isGroup1 = activeTNPSCGroupFilter === 'Group I';
    const sections = isGroup1 ? group1Sections : otherGroupsSections;
    const title = isGroup1 ? 'TNPSC Group I Prelims - Full Mock Test' : 'TNPSC Prelims - Full Mock Test';
    const totalQuestions = sections.reduce((sum, s) => sum + s.questions, 0);

    return (
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <div className="max-w-3xl mx-auto">
                <div className="text-center mb-12">
                    <h2 className="text-3xl font-extrabold text-white">{title}</h2>
                    <p className="mt-4 max-w-2xl mx-auto text-lg text-gray-400">
                        Simulate the complete prelims exam experience with a {totalQuestions}-question mock test generated by AI, covering the entire syllabus as per the official pattern.
                    </p>
                </div>
                <div className="p-8 bg-black/20 rounded-2xl shadow-lg border border-white/10">
                    <h3 className="text-xl font-bold text-white mb-6 text-center">Test Structure</h3>
                    <div className="space-y-4 mb-8">
                         {sections.map(section => (
                            <div key={section.name} className={`p-4 rounded-lg flex justify-between items-center ${section.color} ${section.border}`}>
                                <p className={`font-bold ${section.textColor}`}>{section.name}</p>
                                <p className={`font-semibold text-lg ${section.textColor}`}>{section.questions} Questions</p>
                            </div>
                         ))}
                    </div>
                     <div className="p-4 rounded-lg flex justify-between items-center bg-purple-500/10 border-t-4 border-purple-500">
                        <p className="font-bold text-xl text-purple-200">Total</p>
                        <p className="font-semibold text-2xl text-purple-200">{totalQuestions} Questions</p>
                    </div>

                    <div className="mt-10">
                        <label className="block text-lg font-semibold text-gray-200 mb-4 text-center">
                            Select Difficulty Level
                        </label>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">
                            {difficulties.map((level) => (
                            <button
                                key={level}
                                onClick={() => setSelectedDifficulty(level)}
                                className={`w-full font-semibold rounded-lg px-4 py-2.5 text-md transition-colors duration-200 border ${
                                selectedDifficulty === level
                                    ? 'bg-white text-black border-white'
                                    : 'bg-white/5 text-gray-200 border-white/10 hover:bg-white/10 hover:border-purple-400'
                                }`}
                            >
                                {level}
                            </button>
                            ))}
                        </div>

                        <button
                            onClick={() => onStartTest(selectedDifficulty)}
                            className="btn btn-primary w-full text-xl"
                        >
                            Start Full Mock Test
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default MockTestView;